CREATE TABLE PatientSurveys
(
    patient_survey_id serial primary key,
    provider_id varchar(500) NULL,
    hospital_name varchar(500) NULL,
    address varchar(500) NULL,
    city varchar(500) NULL,
    state varchar(200) NULL,
    zip_code varchar(100) NULL,
    county_name varchar(200) NULL,
    phone_number_type varchar(500) NULL,
    phone_number varchar(300) NULL,
    hcahps_measure_id varchar(200) NULL,
    hcahps_question text NULL,
    hcahps_answer_description text NULL,
    patient_survey_star_rating varchar(100) NULL,
    patient_survey_star_rating_footnote text NULL,
    hcahps_answer_percent varchar(100) NULL,
    hcahps_answer_percent_footnote text NULL,
    hcahps_linear_mean_value varchar(200) NULL,
    number_of_completed_surveys varchar(100) NULL,
    number_of_completed_surveys_footnote text NULL,
    survey_response_rate_percent varchar(100) NULL,
    survey_response_rate_percent_footnote text NULL,
    measure_start_date timestamp NULL,
    measure_end_date timestamp NULL,
    location_city varchar(200) NULL,
    location json NULL,
    location_address varchar(200) NULL,
    location_zip varchar(100) NULL,
    location_state varchar(200) NULL
);