CREATE TABLE PatientSurveys (
    patient_survey_id serial primary key,
    provider_id varchar(50) NULL,
    hospital_name varchar(50) NULL,
    address varchar(50) NULL,
    city varchar(50) NULL,
    state varchar(20) NULL,
    zip_code varchar(10) NULL,
    county_name varchar(20) NULL,
    phone_number_type varchar(50) NULL,
    phone_number varchar(30) NULL,
    hcahps_measure_id varchar(20) NULL,
    hcahps_question text NULL,
    hcahps_answer_description text NULL,
    patient_survey_star_rating varchar(10) NULL,
    patient_survey_star_rating_footnote text NULL,
    hcahps_answer_percent varchar(10) NULL,
    hcahps_answer_percent_footnote text NULL,
    hcahps_linear_mean_value varchar(20) NULL,
    number_of_completed_surveys varchar(10) NULL,
    number_of_completed_surveys_footnote text NULL,
    survey_response_rate_percent varchar(10) NULL,
    survey_response_rate_percent_footnote text NULL,
    measure_start_date timestamp NULL,
    measure_end_date timestamp NULL,
    location_city varchar(20) NULL,
    location json NULL,
    location_address varchar(20) NULL,
    location_zip varchar(10) NULL,
    location_state varchar(20) NULL
);